import SwiftUI
import AppKit

/// The provider mark shown at the left of the menu bar label. Centralized in one
/// place so it can become provider-aware later (per-account icon); today it is
/// fixed to Claude — the official Claude symbol (`Resources/ClaudeGlyph.pdf`,
/// regenerated by `design/glyph/render-glyph.swift`). It's loaded as a TEMPLATE
/// image — only its alpha matters — so AppKit/SwiftUI tint it to the menu bar's
/// foreground color (black on a light bar, white on a dark bar).
struct ProviderGlyph: View {
    /// Glyph height in points — kept a touch under the 13pt label text so the
    /// dense Claude mark reads as a compact companion to the number, not a badge.
    var height: CGFloat = 12

    var body: some View {
        if let image = ProviderGlyph.claude {
            Image(nsImage: image)
                .renderingMode(.template)
                .resizable()
                .interpolation(.high)
                .scaledToFit()
                .frame(height: height)
                .foregroundStyle(.primary) // adaptive: follows the bar (light/dark)
                .accessibilityLabel("Claude")
        } else {
            // Asset missing (e.g. run outside the .app bundle) — stay visible.
            Image(systemName: "sparkles")
                .foregroundStyle(.primary)
                .accessibilityLabel("Claude")
        }
    }

    /// The Claude template image, loaded once from the app bundle. Setting
    /// `isTemplate = true` is what lets the system tint it for the bar appearance.
    static let claude: NSImage? = loadTemplate(named: "ClaudeGlyph")

    private static func loadTemplate(named name: String) -> NSImage? {
        guard let url = Bundle.main.url(forResource: name, withExtension: "pdf"),
              let image = NSImage(contentsOf: url) else { return nil }
        image.isTemplate = true
        return image
    }
}
