import SwiftUI
import AppKit

/// The provider mark shown at the left of the menu bar label. Centralized in one
/// place so it can become provider-aware later (per-account icon); today it is
/// fixed to Claude — the official Claude symbol (`Resources/ClaudeGlyph.pdf`,
/// regenerated by `design/glyph/render-glyph.swift`). It's a TEMPLATE image —
/// only its alpha matters — so the system tints it to the menu bar's foreground
/// color (black on a light bar, white on a dark bar).
///
/// IMPORTANT — sizing: `MenuBarExtra` renders the label's `Image(nsImage:)` at the
/// NSImage's own `size` and IGNORES SwiftUI `.resizable()/.scaledToFit()/.frame()`
/// (a known SwiftUI limitation). So we must resize the *NSImage* itself; otherwise
/// it draws at the PDF's native ~108pt box and overflows the menu bar. We therefore
/// hand SwiftUI an image pre-scaled to `height` points.
struct ProviderGlyph: View {
    /// Rendered icon height in points — a standard menu-bar glyph size that sits
    /// level with the neighboring status items and just above the 13pt label text.
    var height: CGFloat = 16

    var body: some View {
        if let image = ProviderGlyph.sized(height: height) {
            Image(nsImage: image)
                .renderingMode(.template)
                .foregroundStyle(.primary) // adaptive: follows the bar (light/dark)
                .accessibilityLabel("Claude")
        } else {
            // Asset missing (e.g. run outside the .app bundle) — stay visible.
            Image(systemName: "sparkles")
                .foregroundStyle(.primary)
                .accessibilityLabel("Claude")
        }
    }

    /// The Claude template at its native PDF size, loaded once from the app bundle.
    private static let base: NSImage? = loadTemplate(named: "ClaudeGlyph")

    /// A copy of the Claude mark scaled to `height` points (aspect preserved) and
    /// flagged as a template — the form `MenuBarExtra` actually honors. Cheap: the
    /// PDF rep is vector, so the copy stays crisp at any size/scale.
    static func sized(height: CGFloat) -> NSImage? {
        guard let base, base.size.height > 0, let copy = base.copy() as? NSImage else { return nil }
        let aspect = base.size.width / base.size.height
        copy.size = NSSize(width: (height * aspect).rounded(), height: height)
        copy.isTemplate = true
        return copy
    }

    private static func loadTemplate(named name: String) -> NSImage? {
        guard let url = Bundle.main.url(forResource: name, withExtension: "pdf"),
              let image = NSImage(contentsOf: url) else { return nil }
        image.isTemplate = true
        return image
    }
}
